services:
- type: web
  name: agriplatform-backend
  env: python
  plan: standard
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn agriplatform.wsgi:application --bind 0.0.0.0:$PORT
  autoDeploy: true
  envVars:
  - key: DJANGO_SETTINGS_MODULE
    value: agriplatform.settings.prod
  - key: DATABASE_URL
    sync: false
  - key: REDIS_URL
    sync: false
  - key: SECRET_KEY
    sync: false
  - key: RAZORPAY_KEY_ID
    sync: false
  - key: RAZORPAY_KEY_SECRET
    sync: false
  - key: SENDGRID_API_KEY
    sync: false
  - key: FCM_SERVER_KEY
    sync: false
