name: CI

on:
  push:
    paths:
      - 'backend/**'
      - 'frontend/web/**'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - 'backend/**'
      - 'frontend/web/**'

jobs:
  backend:
    name: Backend (Django + PostgreSQL)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: agriplatform
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - '5432:5432'
        options: >-
          --health-cmd="pg_isready -U postgres -d agriplatform"
          --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Django checks and migrations
        env:
          DJANGO_SETTINGS_MODULE: agriplatform.settings.test
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/agriplatform
        run: |
          python manage.py check --deploy --fail-level WARNING || true
          python manage.py migrate --noinput

      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: agriplatform.settings.test
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/agriplatform
        run: |
          python manage.py test --verbosity 2

  frontend:
    name: Frontend (lint + build)
    runs-on: ubuntu-latest
    needs: backend
    defaults:
      run:
        working-directory: frontend/web
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'frontend/web/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint --silent

      - name: Build
        env:
          VITE_API_BASE: http://localhost:8000
        run: npm run build --silent

