name: Frontend CI

on:
  push:
    paths:
      - 'frontend/web/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    paths:
      - 'frontend/web/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/web
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'frontend/web/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint --silent

      - name: Build
        run: npm run build --silent

